// ============================================
// stripe-webhook Lambda
//
// Triggered by API Gateway (POST /stripe-webhook) — but the caller here is
// Stripe itself, not our frontend. After a donor completes Stripe Checkout,
// Stripe calls this endpoint to tell us what happened.
//
// Why a webhook at all, instead of just trusting the browser's redirect
// back to success_url? Because a browser redirect can be faked, closed
// before it happens, or lost to a flaky connection — it's not proof a
// payment actually succeeded. The webhook is Stripe-to-server, signed, and
// is the only source of truth we act on to record a completed donation.
// ============================================

const Stripe = require('stripe');
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand } = require('@aws-sdk/lib-dynamodb');
const { randomUUID } = require('crypto');

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));

const TABLE_NAME = process.env.DONATIONS_TABLE_NAME;
// Generated by Stripe when you register this endpoint (CLI or dashboard);
// used to verify the request really came from Stripe and wasn't forged.
const WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;

exports.handler = async (event) => {
  const signature = event.headers['stripe-signature'] || event.headers['Stripe-Signature'];

  let stripeEvent;
  try {
    // constructEvent verifies the signature using the raw body — this is
    // why API Gateway must be configured to pass the body through
    // untouched (no automatic JSON parsing) for this route.
    stripeEvent = stripe.webhooks.constructEvent(event.body, signature, WEBHOOK_SECRET);
  } catch (err) {
    console.error('Webhook signature verification failed:', err.message);
    return { statusCode: 400, body: `Webhook Error: ${err.message}` };
  }

  if (stripeEvent.type === 'checkout.session.completed') {
    const session = stripeEvent.data.object;

    await ddb.send(new PutCommand({
      TableName: TABLE_NAME,
      Item: {
        id: randomUUID(),
        stripeSessionId: session.id,
        fund: session.metadata?.fund || 'general',
        amount: session.amount_total, // whole taka — see create-checkout-session's comment on BDT minor units
        currency: session.currency,
        donorEmail: session.customer_details?.email || null,
        completedAt: new Date().toISOString(),
      },
    }));
  }

  // Always return 200 for events we don't need to act on — telling Stripe
  // to stop retrying. Only non-2xx responses trigger Stripe's retry logic.
  return { statusCode: 200, body: JSON.stringify({ received: true }) };
};
